name: Generate Pacman Graph

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pacman SVG
        uses: Platane/snk@v3
        with:
          github_user_name: sneh-kheni
          outputs: |
            output/pacman.svg?color_snake=#ff0&color_dots=#000&mode=pacman

      - name: Commit Pacman SVG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/pacman.svg
          git commit -m "Update Pacman graph" || echo "No changes"
          git push
