name: Generate Pacman Graph

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: yoshi389111/github-profile-pacman@main
        with:
          github_user_name: sneh-kheni

      - name: Save pacman graph
        run: |
          mkdir -p output
          mv pacman-contribution-graph.svg output/pacman-contribution-graph.svg

      - name: Commit and push files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/pacman-contribution-graph.svg
          git commit -m "Update pacman graph" || echo "No changes to commit"
          git push
